name: fitness_diet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+1
  provider_architecture: ^1.1.1+1
  date_format: ^1.0.8
  shared_preferences: ^0.5.7+1
  firebase_storage: 4.0.1
  path:
  camera: 0.5.8+10
  path_provider:
  dcdg: ^2.0.1
  intl: ^0.16.1
  photo_view: ^0.10.1
  image_cropper: ^1.2.2
  image_picker: ^0.6.7+12
  flutter_swiper: ^1.1.6
  flutter_custom_dialog: ^1.0.20
  awesome_dialog: ^1.1.3
  timer_count_down: ^1.0.4+1
  age: ^0.0.1
  animator: ^2.0.1
  http: ^0.12.2
  badges: ^1.1.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  lottie: ^0.7.0+1
  async_builder: ^1.2.0
  get_it:
  logger: ^0.7.0+2

  # For designing
  device_preview: ^0.4.3
  carousel_slider: ^1.0.1
  eva_icons_flutter: ^1.0.4
  fleva_icons:
  flutter_spinkit: ^4.1.2
  sleek_circular_slider: ^1.1.0
  flutter_rating_bar: ^3.2.0+1
  searchable_dropdown: ^1.1.3
  dropdown_search:
  animated_widgets: ^1.0.6
  flutter_animator: ^2.1.0
  lite_rolling_switch: ^0.1.1
  custom_switch: ^0.0.1
  flutter_switch: ^0.1.2
  number_inc_dec: ^0.6.6
  font_awesome_flutter: ^8.10.0
  checkbox_grouped: ^0.5.0+1
  fluttertoast: ^7.1.1
  scroll_snap_list: ^0.5.1
  grouped_checkbox: ^1.0.0

  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.2
  cloud_functions:
  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.18.1
  cloud_firestore: ^0.14.1+3
  firebase_core: ^0.5.0
  # otp: ^2.2.1
  flutter_otp: ^0.3.2
  dio: ^3.0.10
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  google_maps_flutter: 0.5.33
  location: ^3.1.0
  flutter_polyline_points: ^0.2.4
  geolocator: ^6.1.13
  cached_network_image: ^2.3.1 #2.0.0-rc.1
  firebase_messaging: 7.0.0 #6.0.13
  flutter_local_notifications: 1.4.4+4 #1.4.0
  #provider package

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/animations/

  fonts:
    - family: Potra
      fonts:
        - asset: assets/fonts/Potra.ttf
    - family: BAHNSCHRIFT
      fonts:
        - asset: assets/fonts/BAHNSCHRIFT.TTF
    - family: Curved-Square
      fonts:
        - asset: assets/fonts/Curved Square.TTF
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
    - family: Proxima-Nova
      fonts:
        - asset: assets/fonts/FontsFree-Net-Proxima-Nova-Bold.otf
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf
    - family: Uni-Sans
      fonts:
        - asset: assets/fonts/Uni-Sans-W01-Regular.ttf
    - family: Lemon-Milk
      fonts:
        - asset: assets/fonts/LEMONMILK-Regular.otf
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf
    - family: BigNoodle
      fonts:
        - asset: assets/fonts/big_noodle_titling.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
